### ISSUE TITLE
Enhancing the UI of theme Toggle

### ISSUE THREAD

**Issue by SahilShaw2004** [riemanndescartes/riemanndescartes.github.io#5]
As of now the ui for toggle is only a button i would like to enhance it .Kindly assign this task to me under Hacktoberfest

**Comment by thekavyakarthik** [comment]
Preferably, make the proposed changes on index.html. We can make your changes reflect to the other portions later

**Comment by SahilShaw2004** [comment]
Label it for Hacktoberfest as well Please😊

**Comment by thekavyakarthik** [comment]
done!

**Comment by thekavyakarthik** [comment]
Thank you!

**Comment by SahilShaw2004** [comment]
Welcome!🙌
