### ISSUE TITLE
Adding website name on the navbar 

### ISSUE THREAD

**Issue by ARRY7686** [riemanndescartes/riemanndescartes.github.io#7]
It is always better to add a website name to the navbar and adjust the navbar accordingly 

I would like to work on it pls assign it to me and mark it as hacktoberfest

**Comment by thekavyakarthik** [comment]
We don't have a logo design in place at the moment. We want to wait until a logo design is ready to do adjust the navigation bar. Do feel free to suggest other changes thought. Thank you for your time.
